/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casaortiz.view;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author jorge
 */
public class ProductoCatalogoView extends javax.swing.JPanel {

    /**
     * Creates new form ProductoImages
     */
    public ProductoCatalogoView() {
        initComponents();
        loadImageGuardada("pro1.jpeg");
    }
    
    
    private void loadImageGuardada(String name) {

        try {
            String string = System.getProperty("user.dir") + "/media/producto/" + name;
            
            Image img = new ImageIcon(string).getImage();
            
            //Me permite redimensionar la imagen para que se adapte al jLabel
            ImageIcon ii = new ImageIcon(img.getScaledInstance(800, 640 , Image.SCALE_SMOOTH));

            jLFoto.setIcon(ii);
            jLFoto.validate();
            jLFoto.repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScroll = new javax.swing.JScrollPane();
        jLFoto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBAtras = new javax.swing.JButton();
        jBSiguiente = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        jScroll.setPreferredSize(new java.awt.Dimension(830, 630));

        jLFoto.setPreferredSize(new java.awt.Dimension(800, 640));
        jScroll.setViewportView(jLFoto);

        jPanel1.add(jScroll, "card2");

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jBAtras.setBackground(new java.awt.Color(194, 60, 61));
        jBAtras.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBAtras.setForeground(java.awt.Color.white);
        jBAtras.setText("<");
        jBAtras.setPreferredSize(new java.awt.Dimension(80, 23));
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(jBAtras);

        jBSiguiente.setBackground(new java.awt.Color(194, 60, 61));
        jBSiguiente.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBSiguiente.setForeground(java.awt.Color.white);
        jBSiguiente.setText(">");
        jBSiguiente.setPreferredSize(new java.awt.Dimension(80, 23));
        jBSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSiguienteActionPerformed(evt);
            }
        });
        jPanel2.add(jBSiguiente);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSiguienteActionPerformed
        // TODO add your handling code here:
        loadImageGuardada("pro2.jpeg");
    }//GEN-LAST:event_jBSiguienteActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        // TODO add your handling code here:
        loadImageGuardada("pro1.jpeg");
    }//GEN-LAST:event_jBAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBSiguiente;
    private javax.swing.JLabel jLFoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScroll;
    // End of variables declaration//GEN-END:variables
}
