/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casaortiz.view;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author jorge
 */
public class ProductoCatalogoView extends javax.swing.JPanel {

    /**
     * Creates new form ProductoImages
     */
    public ProductoCatalogoView() {
        initComponents();
        loadImageGuardada("pro1.jpeg");
    }
    
    
    private void loadImageGuardada(String name) {

        try {
            String string = System.getProperty("user.dir") + "/media/producto/" + name;
            
            Image img = new ImageIcon(string).getImage();
            
            //Me permite redimensionar la imagen para que se adapte al jLabel
            ImageIcon ii = new ImageIcon(img.getScaledInstance(1220, 580, Image.SCALE_SMOOTH));

            jLFoto.setIcon(ii);
            jLFoto.validate();
            jLFoto.repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScroll = new javax.swing.JScrollPane();
        jLFoto = new javax.swing.JLabel();
        jBSiguiente = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScroll.setViewportView(jLFoto);

        add(jScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1220, 580));

        jBSiguiente.setText(">");
        jBSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSiguienteActionPerformed(evt);
            }
        });
        add(jBSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 600, -1, -1));

        jBAtras.setText("<");
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });
        add(jBAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSiguienteActionPerformed
        // TODO add your handling code here:
        loadImageGuardada("pro2.jpeg");
    }//GEN-LAST:event_jBSiguienteActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        // TODO add your handling code here:
        loadImageGuardada("pro1.jpeg");
    }//GEN-LAST:event_jBAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBSiguiente;
    private javax.swing.JLabel jLFoto;
    private javax.swing.JScrollPane jScroll;
    // End of variables declaration//GEN-END:variables
}
